# Generated by Django 5.1.4 on 2024-12-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_apuestas', '0001_initial'),
    ]

    operations = [
    ]
